# This is a basic workflow to help you get started with Actions

name: Test-and-Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint-and-test:
    name: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.0
      - uses: actions/checkout@v3
      - name: vet
        run: |
          go vet .
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
      - name: run test
        run: |
          go test ./...
  # The "build" workflow
  build:
    # The type of runner that the job will run on
    needs: lint-and-test
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.0' # The Go version to download (if necessary) and use.
    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go mod download
        
    # Run build of the application
    - name: Run build
      run: go build . 